# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f710e9d1bf0b574926c32f14bd67f107699b742e45b1e9656d82f485cc4f606a8ea5d4befd00b97235cd7df21b9291a11abe8b91eb6f98811432ad24e5683378

test:
  secret_key_base: 5a4bea6543154d39ad07b066ba69bbc77e5220d947524cd828ab1003f1dc73eb3745104613286e09cb636b0d9614a0148973af2e2029ee28387411b0e296bcba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
